[workspace]
members = ["eighx-assets", "eighx-bindgen",
	"eighx-cli"
, "eighx-editor", "eighx-fft", "eighx-network", "eighx-runtime", "eighx-script", "eighx-ui"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
