[package]
name = "eighx-ui"
version.workspace = true
edition.workspace = true

[lib]
path = "src/ui.rs"

[dependencies]
slint.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true

[build-dependencies]
slint-build = "1.14"
