[package]
name = "eighx-ui"
version.workspace = true
edition.workspace = true

[dependencies]
gpui.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
eighx-ui-macros = { path = "../eighx-ui-macros" }