[package]
name = "eighx-app"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
eighx-ui = { path = "../eighx-ui" }
anyhow.workspace = true
tokio.workspace = true

[[bin]]
name = "eighx"
path = "src/main.rs"
